# Generated by Django 3.1.3 on 2020-11-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='output',
            field=models.TextField(default=''),
        ),
    ]
