# Generated by Django 3.1.3 on 2020-11-22 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        ('command', '0003_command_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='game.game'),
        ),
    ]
