# Generated by Django 3.1.3 on 2020-11-25 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_place_game'),
        ('command', '0004_auto_20201122_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='context',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='place.place'),
        ),
    ]
