# Generated by Django 3.1.3 on 2020-11-27 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_place_game'),
        ('command', '0005_command_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='context',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='place.place'),
        ),
    ]
