# Generated by Django 3.1.3 on 2020-11-27 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_place_game'),
        ('command', '0006_auto_20201127_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='place.place'),
        ),
    ]
