# Generated by Django 3.1.3 on 2020-11-27 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20201122_1740'),
        ('command', '0007_command_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='requirement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='event.event'),
        ),
    ]
