# Generated by Django 3.1.3 on 2020-11-29 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20201122_1740'),
        ('command', '0008_command_requirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reuirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fail', models.TextField(default='')),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='command.command')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
        ),
    ]
