# Generated by Django 3.1.3 on 2020-11-29 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0010_auto_20201129_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='requirement',
        ),
    ]
