# Generated by Django 3.1.3 on 2020-11-29 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0011_remove_command_requirement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='command',
            old_name='output',
            new_name='success',
        ),
    ]
