# Generated by Django 3.1.3 on 2020-11-29 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_place_game'),
        ('command', '0012_auto_20201129_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='context',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commands', to='place.place'),
        ),
        migrations.AlterField(
            model_name='command',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='place.place'),
        ),
    ]
