# Generated by Django 3.1.3 on 2020-11-30 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20201122_1740'),
        ('command', '0013_auto_20201129_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='triggers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commands', to='event.event'),
        ),
    ]
