# Generated by Django 3.1.3 on 2020-11-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0014_command_triggers'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
