# Generated by Django 3.1.3 on 2020-11-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0015_requirement_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
