# Generated by Django 3.1.3 on 2020-12-14 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0016_auto_20201130_1619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requirement',
            options={'ordering': ('-priority',)},
        ),
    ]
