# Generated by Django 3.1.3 on 2020-12-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0017_auto_20201214_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='once',
            field=models.BooleanField(default=False),
        ),
    ]
