# Generated by Django 3.1.3 on 2020-11-29 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_place_game'),
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='place.place'),
        ),
    ]
