# Generated by Django 3.1.3 on 2020-11-29 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_session_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='place',
        ),
    ]
