# Generated by Django 3.1.3 on 2020-11-29 15:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_remove_session_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='last_played',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='session',
            name='started',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
