# Generated by Django 3.1.3 on 2020-11-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20201122_1740'),
        ('player', '0004_auto_20201129_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='happened',
            field=models.ManyToManyField(to='event.Event'),
        ),
    ]
