# Generated by Django 3.1.3 on 2020-12-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0018_command_once'),
        ('player', '0006_session_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='executed',
            field=models.ManyToManyField(to='command.Command'),
        ),
    ]
