# Generated by Django 3.1.3 on 2020-11-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='line_number',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
