# Generated by Django 3.1.3 on 2020-11-13 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_line_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='line_number',
            new_name='chronology',
        ),
    ]
