# Generated by Django 3.1.3 on 2020-11-22 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        ('event', '0003_auto_20201113_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='game',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='game.game'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('name', 'game'), name='unique_event'),
        ),
    ]
