# Generated by Django 3.1.3 on 2020-12-13 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20201122_1740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('chronology',)},
        ),
    ]
