# Generated by Django 3.1.3 on 2020-11-22 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='game',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='places', to='game.game'),
            preserve_default=False,
        ),
    ]
