# Generated by Django 3.1.3 on 2021-02-08 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detailed_output', '0002_auto_20210208_1055'),
        ('place', '0002_place_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='detailed_output.detailedoutput'),
        ),
    ]
