# Generated by Django 3.1.3 on 2021-05-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
