# Generated by Django 3.1.3 on 2021-02-08 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0006_auto_20201213_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailedOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before', models.TextField(default='')),
                ('after', models.TextField(default='')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='event.event')),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='detailed_output.detailedoutput')),
            ],
        ),
    ]
