# Generated by Django 3.1.3 on 2021-01-11 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20201213_1501'),
        ('conversation', '0002_auto_20210111_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conversation.exchange'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='triggers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.event'),
        ),
    ]
