# Generated by Django 3.1.3 on 2021-01-29 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_author'),
        ('conversation', '0003_auto_20210111_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges', to='game.game'),
        ),
    ]
