# Generated by Django 3.1.3 on 2021-05-12 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0004_auto_20210129_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='conversation.exchange'),
        ),
    ]
